{
    'name': 'Asset Management',
    'version': '17.0',
    'summary': 'Manage company assets, transfers, maintenance, and depreciation.',
    'description': """
        Streamline your asset lifecycle management with our comprehensive Odoo module. Track assets, automate depreciation, manage maintenance, and handle transfers effortlessly. Generate detailed reports, monitor warranties, and optimize asset utilization. User-friendly interface ensures easy adoption. Suitable for businesses of all sizes, this module empowers you to make informed decisions and maximize the value of your assets.
    """,
    'category': 'Operations',
    'author': 'WebbyCrown Solutions',
    'website': 'https://www.webbycrown.com',
    'depends': ['base', 'product', 'hr', 'account', 'om_account_asset', 'maintenance', 'mail', 'purchase'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rule.xml',
        'security/maintance_request_rule.xml',
        'security/asset_request_security.xml',
        'data/sequence.xml',
        'views/asset_views.xml',
        'views/asset_search_view.xml',
        'views/res_comapny_inherit.xml',
        'views/account_asset_inherit.xml',
        'views/maintenance_request.xml',
        'views/asset_vendor_views.xml',
        'views/asset_report.xml',
        'views/location_details.xml',
        'views/reference_number_views.xml',
        'views/employee_allocation_service.xml',
        'wizard/update_quantity_views.xml',
        'wizard/renew_service_views.xml',
        'wizard/create_rfq_wizard_views.xml',
        'wizard/asset_register_qty_wizard_views.xml',
        'views/service_asset.xml',
        'views/asset_request_views.xml',
        'views/purchase_order_line_views.xml',
        'views/asset_code_views.xml',

    ],

    'images': ['static/description/asset_img.png', 'static/description/main_screenshot.png', 'static/description/formate_screenshot_1.png',
               'static/description/formate_screenshot_2.png', 'static/description/formate_screenshot_3.png',
               'static/description/formate_screenshot_4.png', 'static/description/formate_screenshot_5.png',
               'static/description/formate_screenshot_6.png', 'static/description/formate_screenshot_7.png'],
    'icon': '/asset_management/static/description/asset_img.png',
    'application': True,
    'installable': True,
    'price': 0,
    'currency': 'EUR',
    'license': 'LGPL-3',
    'assets': {
        'web.assets_backend': [
            'asset_management/static/src/css/asset_tree_style.css',
        ],
    },
}
